---
apiVersion: v1
kind: Secret
metadata:
  name: zebra-service-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/OpenShiftCommons/zebra-java-gitops